FROM python:3.9
RUN apt-get update && apt-get install -y docker.io docker-compose
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY flow.py .
CMD ["python", "flow.py"]
